/*
 * Guessing Game
 * Author: Alex Gioffre'
 * Date: 19-10-2024
 * Description: This program is a simple game where the user must guess a random number
 *              generated by the computer between 1 and 100. The user has only 5 lives
 *              to guess the correct number. The program provides feedback on each of the
 *              user's attempts and keeps track of the number of attempts made.
 */

#include <iostream>
#include <random>
#include <ctime>

int USER_LIVES {5};
bool win = false;

int generate_random_number();
bool check_guessing(int guess, int number);

using namespace std;

int main()
{

  int random_number = generate_random_number();
  cout << "Generate random number... " << endl;

  while(USER_LIVES > 0){
    cout << "User Lives: " << USER_LIVES << endl;
    cout << "Guess the number: ";
    int guess;
    cin >> guess;

    bool game_over = check_guessing(guess, random_number);

    if(game_over)
    { 
      win = true;
      break;
    }
    USER_LIVES--;
  }


  if(win)
    cout << "You Win!!" << endl;
  else
    cout << "You Lose!!" << endl;


  return 0;
}

int generate_random_number()
{
  int random_number{0};

  srand(time(nullptr));

  random_number = rand() % 100 + 1;

  return random_number;
}

bool check_guessing(int guess, int number) {
  if(guess < number){
    cout << "Too Low..." << endl;
    return false;
  }
  else if(guess > number) {
    cout << "Too High..." << endl;
    return false;
  } else {
    return true;
  }
}

